source=~/.config/hypr/hyprland.old/execs.conf
source=~/.config/hypr/hyprland.old/hypr-dynamic-cursor.conf
source=~/.config/hypr/hyprland.old/keybinds.conf
source=~/.config/hypr/hyprland.old/env.conf
source=~/.config/hypr/hyprland.old/general.conf
source=~/.config/hypr/hyprland.old/rules.conf
source=~/.config/hypr/skippy.conf
