# Wallpaper configuration for hyprpaper
# See: https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

# Fallback wallpaper for any other monitors
wallpaper {
    monitor = 
    path = ~/Pictures/backgrounds/1346578.jpg
    fit_mode = cover
}

# Misc options
splash = false
ipc = true
